# Generated by Django 5.2.3 on 2025-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
