# Generated by Django 5.2.3 on 2025-07-08 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_rename_submitted_at_submission_submission_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="code",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="submission_time",
        ),
    ]
