# Generated by Django 5.2.3 on 2025-07-08 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_remove_submission_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
