# Generated by Django 5.2.3 on 2025-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0005_submission_submission_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
