# Generated by Django 5.2.3 on 2025-06-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="admin_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="admin_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="hash_password",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="registration_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
