# Generated by Django 5.2.3 on 2025-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_customuser_admin_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hash_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
