# Generated by Django 5.2.3 on 2025-06-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_customuser_hash_password_alter_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="hash_password",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
