# Generated by Django 5.2.3 on 2025-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_customuser_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("publish_date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
