# Generated by Django 5.2.3 on 2025-06-29 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
