# Generated by Django 5.2.3 on 2025-07-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_alter_challenge_description"),
        ("contests", "0004_usercontest_delete_contestparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="contest",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contests.contest",
            ),
        ),
    ]
