# Generated by Django 5.2.3 on 2025-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0004_usercontest_delete_contestparticipant"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestsubmission",
            name="time_taken",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
