# Generated by Django 5.2.3 on 2025-07-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0006_contestparticipation_delete_usercontest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestsubmission",
            name="time_taken",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
