# Generated by Django 5.2.3 on 2025-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0007_alter_contestsubmission_time_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="contestparticipation",
            name="time_taken",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="contestparticipation",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
